# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/rockylinux8"

  # Provisioning configuration for Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  
  config.vm.network :forwarded_port, guest: 22, host: 2522, auto_correct: false, id: "ssh"
  config.ssh.insert_key = false
  end
end
