# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.name = "rails-demo"
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.hostname = "rails-demo"
  config.vm.network :private_network, ip: "192.168.56.7"
  config.vm.network :forwarded_port, guest: 22, host: 1234, auto_correct: false, id: "ssh"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/main.yml"
    ansible.inventory_path = "/playbooks/inventory-ansible"
    b
  end

end
